name: contactless_payment_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  built_value: ^8.3.2
  rxdart: ^0.27.4
  meta: ^1.7.0
  path: ^1.8.1
  rxdart_ext: ^0.2.2
  tuple: ^2.0.0
  rx_shared_preferences: ^3.0.0
  flow_builder:
  mobile_scanner: ^1.0.0
  built_collection: ^5.1.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2

 
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 
